Add unit tests for burp.Methods
Diffblue-benchmarks/Bit4woo-knife pull request #3
Opened 2019-05-30 12:50 UTC by ThomasPerkins1123

Hi,

I've analysed your code base and noticed that `burp.Methods` in the `knife` module is not fully tested.

I've written some tests that cover this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).

Hopefully, these tests should help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other particular classes that you consider important.

Whilst creating these tests I believe I noticed a small bug with your `do_modify_request` method which I have fixed for you.
Also your source files have been moved into `src/main` to more comfortably allow unit tests.

2019-05-30 14:01 UTC, Braavos6 requested changes
A few lines are longer than 80 characters. I didn't check each line but pretty sure there are some more there

2019-05-30 14:01 UTC, Braavos6 commented on src/test/burp/MethodsTest.java
> +
Remove the extra line

2019-05-30 14:01 UTC, Braavos6 commented on src/test/burp/MethodsTest.java
> +import javax.swing.*;
Try not to import wildcards

2019-05-30 14:01 UTC, Braavos6 commented on src/test/burp/MethodsTest.java
> +    PowerMockito.when(JOptionPane.showInputDialog(anyString(), anyString())).thenReturn("").thenReturn("fooBar");
Line longer than 80 characters

2019-05-30 14:01 UTC, Braavos6 commented on src/test/burp/MethodsTest.java
> +    Assert.assertArrayEquals("3\r\nfoo\r\n3\r\nBar\r\n0\r\n\r\n".getBytes(), Methods.encoding("fooBar".getBytes(), 3, false));
Line longer than 80 characters

2019-05-30 14:01 UTC, Braavos96 commented on src/test/burp/MethodsTest.java
> +    Assert.assertArrayEquals("foo".getBytes(), Methods.do_modify_request("foo".getBytes(), new int[]{3, 2}, null));
Couldn't `testDo_modify_request` and `testDo_modify_requestNull` be squashed into one method as they are testing the same method and only a line long?

2019-06-03 15:09 UTC, paulkennethkent requested changes
Splits this into multiple PRs (slack convo)

2019-06-03 15:29 UTC, closed without merging